# Generated by Django 5.2 on 2025-05-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='identifier_system',
            field=models.CharField(blank=True, default='urn:panacare:patient', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Single'), ('D', 'Divorced'), ('W', 'Widowed'), ('U', 'Unknown')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10),
        ),
    ]
