# Generated by Django 5.2 on 2025-08-25 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Username at time of activity', max_length=150)),
                ('activity', models.CharField(choices=[('login', 'Logged In'), ('logout', 'Logged Out'), ('register', 'User Registration'), ('profile_update', 'Profile Updated'), ('password_change', 'Password Changed'), ('appointment_create', 'Appointment Created'), ('appointment_update', 'Appointment Updated'), ('appointment_cancel', 'Appointment Cancelled'), ('consultation_start', 'Consultation Started'), ('consultation_end', 'Consultation Ended'), ('article_create', 'Article Created'), ('article_update', 'Article Updated'), ('article_approve', 'Article Approved'), ('article_reject', 'Article Rejected'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('role_assign', 'Role Assigned'), ('subscription_create', 'Subscription Created'), ('payment_process', 'Payment Processed'), ('data_export', 'Data Exported'), ('system_access', 'System Access'), ('api_access', 'API Access'), ('other', 'Other Activity')], help_text='Type of activity performed', max_length=50)),
                ('email_address', models.EmailField(help_text='Email address at time of activity', max_length=254)),
                ('role', models.CharField(help_text='User roles at time of activity', max_length=100)),
                ('time_spent', models.DurationField(blank=True, help_text='Time spent on activity', null=True)),
                ('date_joined', models.DateTimeField(help_text='When the user joined the system')),
                ('last_active', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='active', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('session_id', models.CharField(blank=True, help_text='Session identifier', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional activity details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_audit_user_id_949877_idx'), models.Index(fields=['activity', '-created_at'], name='users_audit_activit_941bea_idx'), models.Index(fields=['status', '-created_at'], name='users_audit_status_f7449b_idx')],
            },
        ),
    ]
