# Generated by Django 5.2 on 2025-12-17 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityHealthProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certification_number', models.CharField(blank=True, help_text='Certification or license number', max_length=50)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('specialization', models.CharField(blank=True, help_text='Area of specialization (e.g., maternal health, nutrition)', max_length=200)),
                ('service_area', models.CharField(blank=True, help_text='Geographic area of service', max_length=200)),
                ('languages_spoken', models.CharField(blank=True, help_text='Languages spoken (comma-separated)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('availability_hours', models.CharField(blank=True, help_text='Available hours (e.g., Mon-Fri 9AM-5PM)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_health_provider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Health Provider',
                'verbose_name_plural': 'Community Health Providers',
            },
        ),
    ]
