# Generated by Django 5.2 on 2025-12-17 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_created_by_chp_to_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_by_chp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to='users.communityhealthprovider'),
        ),
    ]
