# Generated by Django 5.2.3 on 2025-12-26 10:06

from django.db import migrations
from django.core.management import call_command


def load_location_data(apps, schema_editor):
    """Load initial location data from fixture"""
    try:
        call_command('loaddata', 'users/fixtures/locations.json', verbosity=0)
    except Exception as e:
        print(f"Failed to load location data: {e}")


def reverse_location_data(apps, schema_editor):
    """Remove location data"""
    Location = apps.get_model('users', 'Location')
    Location.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_created_by_chp_to_patient'),
    ]

    operations = [
        migrations.RunPython(load_location_data, reverse_location_data),
    ]
