# Generated by Django 5.2.3 on 2026-02-02 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_chppatientmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(help_text='Professional license number', max_length=100, unique=True)),
                ('license_type', models.CharField(blank=True, help_text='Type of license (e.g., RN, NP, PA, Clinical Officer)', max_length=100)),
                ('issuing_authority', models.CharField(blank=True, help_text='Licensing board or authority', max_length=200)),
                ('license_expiry_date', models.DateField(blank=True, help_text='License expiration date', null=True)),
                ('qualification', models.CharField(blank=True, help_text='Highest qualification (e.g., BSN, MSN, Diploma)', max_length=200)),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Years of clinical experience')),
                ('specialization', models.CharField(blank=True, help_text='Clinical specialization (e.g., Emergency Care, Pediatrics, ICU)', max_length=200)),
                ('professional_bio', models.TextField(blank=True, help_text='Professional biography')),
                ('skills', models.TextField(blank=True, help_text='Key clinical skills and competencies')),
                ('certifications', models.TextField(blank=True, help_text='Additional certifications (comma-separated)')),
                ('department', models.CharField(blank=True, help_text='Department or unit', max_length=200)),
                ('facility_name', models.CharField(blank=True, help_text='Healthcare facility name', max_length=200)),
                ('is_verified', models.BooleanField(default=False, help_text="Whether the clinician's credentials are verified")),
                ('is_active', models.BooleanField(default=True, help_text='Whether the clinician is active in the system')),
                ('verification_date', models.DateTimeField(blank=True, help_text='Date when credentials were verified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinician', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified this clinician', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_clinicians', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinician',
                'verbose_name_plural': 'Clinicians',
                'ordering': ['-created_at'],
            },
        ),
    ]
