# Generated by Django 5.2.3 on 2026-02-02 17:23

from django.db import migrations


def create_clinician_role(apps, schema_editor):
    """
    Create the clinician role in the database
    """
    Role = apps.get_model('users', 'Role')

    # Create clinician role if it doesn't exist
    Role.objects.get_or_create(
        name='clinician',
        defaults={
            'description': 'Licensed clinical healthcare professional (nurse, PA, clinical officer, etc.)'
        }
    )


def remove_clinician_role(apps, schema_editor):
    """
    Remove the clinician role (reverse migration)
    """
    Role = apps.get_model('users', 'Role')
    Role.objects.filter(name='clinician').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_clinician'),
    ]

    operations = [
        migrations.RunPython(create_clinician_role, remove_clinician_role),
    ]
