# Generated by Django 5.2.3 on 2026-02-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_clinician_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='health_notes',
            field=models.TextField(blank=True, help_text='Recent symptoms and health notes'),
        ),
    ]
