# Generated by Django 5.2.3 on 2026-02-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_patient_health_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_url',
            field=models.URLField(blank=True, help_text="URL to user's profile picture", max_length=500),
        ),
    ]
