# Generated by Django 5.2.3 on 2026-02-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_url',
            field=models.URLField(blank=True, help_text="URL to user's profile picture", max_length=500, null=True),
        ),
    ]
