# Generated by Django 5.2 on 2025-04-22 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0003_education_alter_doctor_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General Healthcare'), ('PEDIATRIC', 'Pediatric Healthcare'), ('MENTAL', 'Mental Healthcare'), ('DENTAL', 'Dental Healthcare'), ('VISION', 'Vision Healthcare'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctors', models.ManyToManyField(blank=True, related_name='healthcare_facilities', to='doctors.doctor')),
            ],
        ),
    ]
