# Generated by Django 5.2 on 2025-05-15 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_patientdoctorassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcare',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='country',
            field=models.CharField(blank=True, default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='identifier_system',
            field=models.CharField(blank=True, default='urn:panacare:organization', max_length=255),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='part_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_organizations', to='healthcare.healthcare'),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='encounter_type',
            field=models.CharField(choices=[('AMB', 'Ambulatory'), ('EMER', 'Emergency'), ('FLD', 'Field'), ('HH', 'Home Health'), ('IMP', 'Inpatient Acute'), ('VR', 'Virtual'), ('OBS', 'Observation'), ('OP', 'Outpatient'), ('SS', 'Standard Scheduled')], default='SS', max_length=10),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='healthcare_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='healthcare.healthcare'),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='identifier_system',
            field=models.CharField(blank=True, default='urn:panacare:encounter', max_length=255),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('arrived', 'Arrived'), ('triaged', 'Triaged'), ('in-progress', 'In Progress'), ('onleave', 'On Leave'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('entered-in-error', 'Entered in Error'), ('unknown', 'Unknown')], default='planned', max_length=20),
        ),
    ]
