# Generated by Django 5.2 on 2025-05-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_healthcare_city_healthcare_country_and_more'),
        ('users', '0003_remove_customer_user_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdoctorassignment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='users.patient'),
        ),
    ]
