# Generated by Django 5.2 on 2025-05-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_package_appointment_appointmentdocument_consultation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('routine', 'Routine Checkup'), ('follow-up', 'Follow Up'), ('emergency', 'Emergency'), ('consultation', 'Consultation'), ('procedure', 'Procedure'), ('checkup', 'Checkup'), ('other', 'Other')], default='consultation', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('pending', 'Pending'), ('booked', 'Booked'), ('arrived', 'Arrived'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('noshow', 'No Show'), ('scheduled', 'Scheduled'), ('entered-in-error', 'Entered in Error')], default='booked', max_length=20),
        ),
    ]
