# Generated by Django 5.2 on 2025-06-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0006_alter_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='doctor_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='twilio_room_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultation',
            name='twilio_room_sid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
