# Generated by Django 5.2.3 on 2025-07-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0008_article_articlecomment_consultationchat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patientsubscription',
            name='package',
        ),
        migrations.RemoveField(
            model_name='patientsubscription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='author',
        ),
        migrations.RemoveField(
            model_name='healthcare',
            name='doctors',
        ),
        migrations.RemoveField(
            model_name='patientdoctorassignment',
            name='actual_end',
        ),
        migrations.RemoveField(
            model_name='patientdoctorassignment',
            name='actual_start',
        ),
        migrations.RemoveField(
            model_name='patientdoctorassignment',
            name='encounter_type',
        ),
        migrations.RemoveField(
            model_name='patientdoctorassignment',
            name='healthcare_facility',
        ),
        migrations.RemoveField(
            model_name='patientdoctorassignment',
            name='identifier_system',
        ),
        migrations.RemoveField(
            model_name='patientdoctorassignment',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='patientdoctorassignment',
            name='scheduled_end',
        ),
        migrations.RemoveField(
            model_name='patientdoctorassignment',
            name='scheduled_start',
        ),
        migrations.RemoveField(
            model_name='patientdoctorassignment',
            name='status',
        ),
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='reading_time',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='article',
            name='related_conditions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Available to all users'), ('subscribers', 'Subscribers Only - Available to paying patients'), ('private', 'Private - Only visible to author and admins')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AppointmentDocument',
        ),
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='PatientSubscription',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
