# Generated by Django 5.2.3 on 2025-07-23 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0011_payment_patientsubscription_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='encounter_type',
            field=models.CharField(choices=[('AMB', 'Ambulatory'), ('EMER', 'Emergency'), ('FLD', 'Field'), ('HH', 'Home Health'), ('IMP', 'Inpatient Acute'), ('VR', 'Virtual'), ('OBS', 'Observation'), ('OP', 'Outpatient'), ('SS', 'Standard Scheduled')], default='AMB', max_length=10),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='healthcare_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_assignments', to='healthcare.healthcare'),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='identifier_system',
            field=models.CharField(blank=True, default='urn:panacare:encounter', max_length=255),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdoctorassignment',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('arrived', 'Arrived'), ('triaged', 'Triaged'), ('in-progress', 'In Progress'), ('onleave', 'On Leave'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('entered-in-error', 'Entered in Error'), ('unknown', 'Unknown')], default='in-progress', max_length=20),
        ),
    ]
