# Generated by Django 5.2.3 on 2025-12-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0013_article_is_rejected_article_rejected_by_and_more'),
        ('users', '0005_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientJournal',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('preview', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='users.patient')),
            ],
            options={
                'verbose_name': 'Patient Journal',
                'verbose_name_plural': 'Patient Journals',
                'ordering': ['-created_at'],
            },
        ),
    ]
