# Generated by Django 5.2 on 2025-12-17 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0014_patientjournal'),
        ('users', '0007_add_created_by_chp_to_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_by_chp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to='users.communityhealthprovider'),
        ),
    ]
