# Generated by Django 5.2.3 on 2026-01-09 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctor_accepts_referrals_doctor_consultation_modes_and_more'),
        ('healthcare', '0015_add_created_by_chp_to_appointment'),
        ('users', '0010_chppatientmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_reason', models.TextField(help_text='Reason for referral')),
                ('clinical_notes', models.TextField(blank=True, help_text='Additional clinical observations')),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('asap', 'ASAP'), ('stat', 'STAT')], default='routine', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('follow_up_required', models.BooleanField(default=True)),
                ('follow_up_notes', models.TextField(blank=True, help_text='Follow-up instructions or notes')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, help_text="Doctor's notes on the referral")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='users.patient')),
                ('referred_to_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='doctors.doctor')),
                ('referring_chp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='users.communityhealthprovider')),
            ],
            options={
                'verbose_name': 'Patient Referral',
                'verbose_name_plural': 'Patient Referrals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referring_chp', 'status'], name='healthcare__referri_45ef26_idx'), models.Index(fields=['referred_to_doctor', 'status'], name='healthcare__referre_7e032c_idx'), models.Index(fields=['patient', 'status'], name='healthcare__patient_ec71fc_idx'), models.Index(fields=['created_at'], name='healthcare__created_322af6_idx')],
            },
        ),
    ]
