# Generated by Django 5.2 on 2025-05-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_education_alter_doctor_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='communication_languages',
            field=models.CharField(blank=True, default='en', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='identifier_system',
            field=models.CharField(blank=True, default='urn:panacare:practitioner', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_system',
            field=models.CharField(blank=True, default='urn:panacare:license', max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
