# Generated by Django 5.2 on 2025-06-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_communication_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='accepts_referrals',
            field=models.BooleanField(default=True, help_text='Whether the doctor accepts patient referrals'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_modes',
            field=models.CharField(default='audio,video', help_text='Comma-separated list of consultation modes (audio,video)', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='facility_name',
            field=models.CharField(blank=True, help_text="Name of the doctor's primary healthcare facility", max_length=255),
        ),
    ]
