# Generated by Django 5.2 on 2025-05-24 14:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalDecisionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('height', models.FloatField(help_text='Height in centimeters')),
                ('high_blood_pressure', models.BooleanField(default=False, help_text='Has the patient been diagnosed with high blood pressure?')),
                ('diabetes', models.BooleanField(default=False, help_text='Has the patient been diagnosed with diabetes?')),
                ('on_medication', models.BooleanField(default=False, help_text='Is the patient currently on medication?')),
                ('headache', models.BooleanField(default=False)),
                ('dizziness', models.BooleanField(default=False)),
                ('blurred_vision', models.BooleanField(default=False)),
                ('palpitations', models.BooleanField(default=False)),
                ('fatigue', models.BooleanField(default=False)),
                ('chest_pain', models.BooleanField(default=False)),
                ('frequent_thirst', models.BooleanField(default=False)),
                ('loss_of_appetite', models.BooleanField(default=False)),
                ('frequent_urination', models.BooleanField(default=False)),
                ('other_symptoms', models.TextField(blank=True, null=True)),
                ('no_symptoms', models.BooleanField(default=False, help_text='None of the above symptoms')),
                ('systolic_pressure', models.IntegerField(blank=True, help_text='Systolic blood pressure', null=True)),
                ('diastolic_pressure', models.IntegerField(blank=True, help_text='Diastolic blood pressure', null=True)),
                ('blood_sugar', models.FloatField(blank=True, help_text='Blood sugar in mg/dL', null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart rate in BPM', null=True)),
                ('sleep_hours', models.FloatField(blank=True, help_text='Hours of sleep per day', null=True)),
                ('exercise_minutes', models.IntegerField(blank=True, help_text='Minutes of exercise per day', null=True)),
                ('eats_unhealthy', models.BooleanField(default=False, help_text='Regularly eats salty or sugary foods')),
                ('smokes', models.BooleanField(default=False, help_text='Patient smokes')),
                ('consumes_alcohol', models.BooleanField(default=False, help_text='Patient consumes alcohol')),
                ('skips_medication', models.BooleanField(default=False, help_text='Patient sometimes skips medication')),
                ('analysis', models.TextField(blank=True, help_text='Analysis of patient data', null=True)),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations based on analysis', null=True)),
                ('risk_level', models.CharField(blank=True, help_text='Assessed risk level', max_length=20, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_decisions', to='users.patient')),
            ],
        ),
    ]
