# Generated by Django 5.2.3 on 2025-12-29 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_appointments', models.BooleanField(default=True)),
                ('push_consultations', models.BooleanField(default=True)),
                ('push_payments', models.BooleanField(default=True)),
                ('push_subscriptions', models.BooleanField(default=True)),
                ('push_articles', models.BooleanField(default=True)),
                ('push_emergency', models.BooleanField(default=True)),
                ('push_announcements', models.BooleanField(default=True)),
                ('push_reminders', models.BooleanField(default=True)),
                ('push_general', models.BooleanField(default=True)),
                ('email_appointments', models.BooleanField(default=False)),
                ('email_consultations', models.BooleanField(default=False)),
                ('email_payments', models.BooleanField(default=True)),
                ('email_subscriptions', models.BooleanField(default=True)),
                ('email_articles', models.BooleanField(default=False)),
                ('email_emergency', models.BooleanField(default=True)),
                ('email_announcements', models.BooleanField(default=False)),
                ('email_reminders', models.BooleanField(default=True)),
                ('email_general', models.BooleanField(default=False)),
                ('sms_appointments', models.BooleanField(default=False)),
                ('sms_consultations', models.BooleanField(default=False)),
                ('sms_payments', models.BooleanField(default=False)),
                ('sms_subscriptions', models.BooleanField(default=False)),
                ('sms_articles', models.BooleanField(default=False)),
                ('sms_emergency', models.BooleanField(default=True)),
                ('sms_announcements', models.BooleanField(default=False)),
                ('sms_reminders', models.BooleanField(default=True)),
                ('sms_general', models.BooleanField(default=False)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(default='22:00')),
                ('quiet_hours_end', models.TimeField(default='08:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preferences',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('appointment', 'Appointment'), ('consultation', 'Consultation'), ('payment', 'Payment'), ('subscription', 'Subscription'), ('article', 'Article'), ('emergency', 'Emergency'), ('announcement', 'Announcement'), ('reminder', 'Reminder'), ('general', 'General')], default='general', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification History',
                'verbose_name_plural': 'Notification History',
                'db_table': 'notification_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_7f8945_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_32a536_idx'), models.Index(fields=['created_at'], name='notificatio_created_307e3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopicSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('all_users', 'All Users'), ('doctors', 'Doctors'), ('patients', 'Patients'), ('admins', 'Administrators'), ('emergencies', 'Emergency Alerts'), ('announcements', 'General Announcements'), ('health_tips', 'Health Tips'), ('system_updates', 'System Updates')], max_length=50)),
                ('subscribed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic Subscription',
                'verbose_name_plural': 'Topic Subscriptions',
                'db_table': 'topic_subscriptions',
                'indexes': [models.Index(fields=['topic', 'subscribed'], name='topic_subsc_topic_d48ad1_idx')],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
